spring:
  application:
    name: "jenkins-api-springboot"
  profiles:
    group:
      "prod": "prod, default"
      "dev": "dev, default"
      "staging": "staging, default"
---
spring:
  config.activate.on-profile: "dev"
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  datasource:
    initialization-mode: always
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:jenkins
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-admin-password: choshsh
server:
  port: 8081
management:
  endpoints:
    web:
      base-path: "/actuator"
      exposure:
        include:
          - health
          - prometheus
---
spring:
  config.activate.on-profile: "prod"
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  datasource:
    initialization-mode: never
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
server:
  port: 8080
management:
  endpoints:
    web:
      base-path: ${ACTUATOR_PATH}
      exposure:
        include:
          - health
          - prometheus
---
jenkins:
  pyscriptURL: "https://api.github.com/repos/choshsh/devops-study/git/trees/master?recursive=3"
spring: # default
  config.activate.on-profile: "default"
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    open-in-view: false
    properties.hibernate.format_sql: false
    hibernate:
      use-new-id-generator-mappings: true
logging:
  level:
    web: warn
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    #console: "{\"timestamp\": \"%d\", \"level\": \"%p\", \"source\": \"%logger{63}:%L\", \"message\": \"%replace(%m%wEx{6}){'[\r\n]+', '\\n'}%nopex\"}%n"
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
server:
  compression:
    enabled: true
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 14400
